import pygame
import os

pygame.init()

list_image_name = [
    "Astronauts/spaceAstronauts_001.png",
    "Astronauts/spaceAstronauts_002.png",
    "Astronauts/spaceAstronauts_003.png",
    "Astronauts/spaceAstronauts_004.png",
    "Astronauts/spaceAstronauts_005.png",
    "Astronauts/spaceAstronauts_006.png",
    "Astronauts/spaceAstronauts_007.png",
    "Astronauts/spaceAstronauts_008.png",
    "Astronauts/spaceAstronauts_009.png",
    "Astronauts/spaceAstronauts_010.png",
    "Astronauts/spaceAstronauts_011.png",
    "Astronauts/spaceAstronauts_012.png",
    "Astronauts/spaceAstronauts_013.png",
    "Astronauts/spaceAstronauts_014.png",
    "Astronauts/spaceAstronauts_015.png",
    "Astronauts/spaceAstronauts_016.png",
    "Astronauts/spaceAstronauts_017.png",
    "Astronauts/spaceAstronauts_018.png",
    "Building/spaceBuilding_001.png",
    "Building/spaceBuilding_002.png",
    "Building/spaceBuilding_003.png",
    "Building/spaceBuilding_004.png",
    "Building/spaceBuilding_005.png",
    "Building/spaceBuilding_006.png",
    "Building/spaceBuilding_007.png",
    "Building/spaceBuilding_008.png",
    "Building/spaceBuilding_009.png",
    "Building/spaceBuilding_010.png",
    "Building/spaceBuilding_011.png",
    "Building/spaceBuilding_012.png",
    "Building/spaceBuilding_013.png",
    "Building/spaceBuilding_014.png",
    "Building/spaceBuilding_015.png",
    "Building/spaceBuilding_016.png",
    "Building/spaceBuilding_017.png",
    "Building/spaceBuilding_018.png",
    "Building/spaceBuilding_019.png",
    "Building/spaceBuilding_020.png",
    "Building/spaceBuilding_021.png",
    "Building/spaceBuilding_022.png",
    "Building/spaceBuilding_023.png",
    "Building/spaceBuilding_024.png",
    "Building/spaceBuilding_025.png",
    "Effects/spaceEffects_001.png",
    "Effects/spaceEffects_002.png",
    "Effects/spaceEffects_003.png",
    "Effects/spaceEffects_004.png",
    "Effects/spaceEffects_005.png",
    "Effects/spaceEffects_006.png",
    "Effects/spaceEffects_007.png",
    "Effects/spaceEffects_008.png",
    "Effects/spaceEffects_009.png",
    "Effects/spaceEffects_010.png",
    "Effects/spaceEffects_011.png",
    "Effects/spaceEffects_012.png",
    "Effects/spaceEffects_013.png",
    "Effects/spaceEffects_014.png",
    "Effects/spaceEffects_015.png",
    "Effects/spaceEffects_016.png",
    "Effects/spaceEffects_017.png",
    "Effects/spaceEffects_018.png",
    "Meteors/spaceMeteors_001.png",
    "Meteors/spaceMeteors_002.png",
    "Meteors/spaceMeteors_003.png",
    "Meteors/spaceMeteors_004.png",
    "Missiles/spaceMissiles_001.png",
    "Missiles/spaceMissiles_002.png",
    "Missiles/spaceMissiles_003.png",
    "Missiles/spaceMissiles_004.png",
    "Missiles/spaceMissiles_005.png",
    "Missiles/spaceMissiles_006.png",
    "Missiles/spaceMissiles_007.png",
    "Missiles/spaceMissiles_008.png",
    "Missiles/spaceMissiles_009.png",
    "Missiles/spaceMissiles_010.png",
    "Missiles/spaceMissiles_011.png",
    "Missiles/spaceMissiles_012.png",
    "Missiles/spaceMissiles_013.png",
    "Missiles/spaceMissiles_014.png",
    "Missiles/spaceMissiles_015.png",
    "Missiles/spaceMissiles_016.png",
    "Missiles/spaceMissiles_017.png",
    "Missiles/spaceMissiles_018.png",
    "Missiles/spaceMissiles_019.png",
    "Missiles/spaceMissiles_020.png",
    "Missiles/spaceMissiles_021.png",
    "Missiles/spaceMissiles_022.png",
    "Missiles/spaceMissiles_023.png",
    "Missiles/spaceMissiles_024.png",
    "Missiles/spaceMissiles_025.png",
    "Missiles/spaceMissiles_026.png",
    "Missiles/spaceMissiles_027.png",
    "Missiles/spaceMissiles_028.png",
    "Missiles/spaceMissiles_029.png",
    "Missiles/spaceMissiles_030.png",
    "Missiles/spaceMissiles_031.png",
    "Missiles/spaceMissiles_032.png",
    "Missiles/spaceMissiles_033.png",
    "Missiles/spaceMissiles_034.png",
    "Missiles/spaceMissiles_035.png",
    "Missiles/spaceMissiles_036.png",
    "Missiles/spaceMissiles_037.png",
    "Missiles/spaceMissiles_038.png",
    "Missiles/spaceMissiles_039.png",
    "Missiles/spaceMissiles_040.png",
    "Parts/spaceParts_001.png",
    "Parts/spaceParts_002.png",
    "Parts/spaceParts_003.png",
    "Parts/spaceParts_004.png",
    "Parts/spaceParts_005.png",
    "Parts/spaceParts_006.png",
    "Parts/spaceParts_007.png",
    "Parts/spaceParts_008.png",
    "Parts/spaceParts_009.png",
    "Parts/spaceParts_010.png",
    "Parts/spaceParts_011.png",
    "Parts/spaceParts_012.png",
    "Parts/spaceParts_013.png",
    "Parts/spaceParts_014.png",
    "Parts/spaceParts_015.png",
    "Parts/spaceParts_016.png",
    "Parts/spaceParts_017.png",
    "Parts/spaceParts_018.png",
    "Parts/spaceParts_019.png",
    "Parts/spaceParts_020.png",
    "Parts/spaceParts_021.png",
    "Parts/spaceParts_022.png",
    "Parts/spaceParts_023.png",
    "Parts/spaceParts_024.png",
    "Parts/spaceParts_025.png",
    "Parts/spaceParts_026.png",
    "Parts/spaceParts_027.png",
    "Parts/spaceParts_028.png",
    "Parts/spaceParts_029.png",
    "Parts/spaceParts_030.png",
    "Parts/spaceParts_031.png",
    "Parts/spaceParts_032.png",
    "Parts/spaceParts_033.png",
    "Parts/spaceParts_034.png",
    "Parts/spaceParts_035.png",
    "Parts/spaceParts_036.png",
    "Parts/spaceParts_037.png",
    "Parts/spaceParts_038.png",
    "Parts/spaceParts_039.png",
    "Parts/spaceParts_040.png",
    "Parts/spaceParts_041.png",
    "Parts/spaceParts_042.png",
    "Parts/spaceParts_043.png",
    "Parts/spaceParts_044.png",
    "Parts/spaceParts_045.png",
    "Parts/spaceParts_046.png",
    "Parts/spaceParts_047.png",
    "Parts/spaceParts_048.png",
    "Parts/spaceParts_049.png",
    "Parts/spaceParts_050.png",
    "Parts/spaceParts_051.png",
    "Parts/spaceParts_052.png",
    "Parts/spaceParts_053.png",
    "Parts/spaceParts_054.png",
    "Parts/spaceParts_055.png",
    "Parts/spaceParts_056.png",
    "Parts/spaceParts_057.png",
    "Parts/spaceParts_058.png",
    "Parts/spaceParts_059.png",
    "Parts/spaceParts_060.png",
    "Parts/spaceParts_061.png",
    "Parts/spaceParts_062.png",
    "Parts/spaceParts_063.png",
    "Parts/spaceParts_064.png",
    "Parts/spaceParts_065.png",
    "Parts/spaceParts_066.png",
    "Parts/spaceParts_067.png",
    "Parts/spaceParts_068.png",
    "Parts/spaceParts_069.png",
    "Parts/spaceParts_070.png",
    "Parts/spaceParts_071.png",
    "Parts/spaceParts_072.png",
    "Parts/spaceParts_073.png",
    "Parts/spaceParts_074.png",
    "Parts/spaceParts_075.png",
    "Parts/spaceParts_076.png",
    "Parts/spaceParts_077.png",
    "Parts/spaceParts_078.png",
    "Parts/spaceParts_079.png",
    "Parts/spaceParts_080.png",
    "Parts/spaceParts_081.png",
    "Parts/spaceParts_082.png",
    "Parts/spaceParts_083.png",
    "Parts/spaceParts_084.png",
    "Parts/spaceParts_085.png",
    "Parts/spaceParts_086.png",
    "Parts/spaceParts_087.png",
    "Parts/spaceParts_088.png",
    "Parts/spaceParts_089.png",
    "Parts/spaceParts_090.png",
    "Parts/spaceParts_091.png",
    "Parts/spaceParts_092.png",
    "Parts/spaceParts_093.png",
    "Parts/spaceParts_094.png",
    "Parts/spaceParts_095.png",
    "Parts/spaceParts_096.png",
    "Parts/spaceParts_097.png",
    "Parts/spaceParts_098.png",
    "planets/planet00.png",
    "planets/planet01.png",
    "planets/planet02.png",
    "planets/planet03.png",
    "planets/planet04.png",
    "planets/planet05.png",
    "planets/planet06.png",
    "planets/planet07.png",
    "planets/planet08.png",
    "planets/planet09.png",
    "Rocket parts/spaceRocketparts_001.png",
    "Rocket parts/spaceRocketparts_002.png",
    "Rocket parts/spaceRocketparts_003.png",
    "Rocket parts/spaceRocketparts_004.png",
    "Rocket parts/spaceRocketparts_005.png",
    "Rocket parts/spaceRocketparts_006.png",
    "Rocket parts/spaceRocketparts_007.png",
    "Rocket parts/spaceRocketparts_008.png",
    "Rocket parts/spaceRocketparts_009.png",
    "Rocket parts/spaceRocketparts_010.png",
    "Rocket parts/spaceRocketparts_011.png",
    "Rocket parts/spaceRocketparts_012.png",
    "Rocket parts/spaceRocketparts_013.png",
    "Rocket parts/spaceRocketparts_014.png",
    "Rocket parts/spaceRocketparts_015.png",
    "Rocket parts/spaceRocketparts_016.png",
    "Rocket parts/spaceRocketparts_017.png",
    "Rocket parts/spaceRocketparts_018.png",
    "Rocket parts/spaceRocketparts_019.png",
    "Rocket parts/spaceRocketparts_020.png",
    "Rocket parts/spaceRocketparts_021.png",
    "Rocket parts/spaceRocketparts_022.png",
    "Rocket parts/spaceRocketparts_023.png",
    "Rocket parts/spaceRocketparts_024.png",
    "Rocket parts/spaceRocketparts_025.png",
    "Rocket parts/spaceRocketparts_026.png",
    "Rocket parts/spaceRocketparts_027.png",
    "Rocket parts/spaceRocketparts_028.png",
    "Rocket parts/spaceRocketparts_029.png",
    "Rocket parts/spaceRocketparts_030.png",
    "Rocket parts/spaceRocketparts_031.png",
    "Rockets/spaceRockets_001.png",
    "Rockets/spaceRockets_002.png",
    "Rockets/spaceRockets_003.png",
    "Rockets/spaceRockets_004.png",
    "Ships/spaceShips_001.png",
    "Ships/spaceShips_002.png",
    "Ships/spaceShips_003.png",
    "Ships/spaceShips_004.png",
    "Ships/spaceShips_005.png",
    "Ships/spaceShips_006.png",
    "Ships/spaceShips_007.png",
    "Ships/spaceShips_008.png",
    "Ships/spaceShips_009.png",
    "Station/spaceStation_001.png",
    "Station/spaceStation_002.png",
    "Station/spaceStation_003.png",
    "Station/spaceStation_004.png",
    "Station/spaceStation_005.png",
    "Station/spaceStation_006.png",
    "Station/spaceStation_007.png",
    "Station/spaceStation_008.png",
    "Station/spaceStation_009.png",
    "Station/spaceStation_010.png",
    "Station/spaceStation_011.png",
    "Station/spaceStation_012.png",
    "Station/spaceStation_013.png",
    "Station/spaceStation_014.png",
    "Station/spaceStation_015.png",
    "Station/spaceStation_016.png",
    "Station/spaceStation_017.png",
    "Station/spaceStation_018.png",
    "Station/spaceStation_019.png",
    "Station/spaceStation_020.png",
    "Station/spaceStation_021.png",
    "Station/spaceStation_022.png",
    "Station/spaceStation_023.png",
    "Station/spaceStation_024.png",
    "Station/spaceStation_025.png",
    "Station/spaceStation_026.png",
    "Station/spaceStation_027.png",
    "Station/spaceStation_028.png",
    "Station/spaceStation_029.png",
    "Station/spaceStation_030.png",
    "Station/spaceStation_031.png",
]


class ImageLoad:
    def __init__(self):
        self.image_dict = {}
        for name in list_image_name:
            image = pygame.image.load(name)
            # Sprawdzanie, czy obrazek ma kanał alfa i konwersja
            if image.get_alpha():
                self.image_dict[name] = image.convert_alpha()
            else:
                self.image_dict[name] = image.convert()

    def get_image(self, name, scale):
        image = self.image_dict.get(name)
        ret = None
        if not image:
            ret = None
        elif isinstance(scale, (list, tuple)):
            if len(scale) == 2:
                width, height = scale
                ret = pygame.transform.scale(image, (width, height))
            elif len(scale) == 1:
                percent = scale[0] / 100
                width = int(image.get_width() * percent)
                height = int(image.get_height() * percent)
                ret = pygame.transform.scale(image, (width, height))
        elif isinstance(scale, (int, float)):
            percent = scale / 100
            width = int(image.get_width() * percent)
            height = int(image.get_height() * percent)
            ret = pygame.transform.scale(image, (width, height))
        
        return ret