import pygame
import os

pygame.init()

list_image_name = [
  "images/space_ships/playerShip1_blue.png",
  "images/space_ships/playerShip1_green.png",
  "images/space_ships/playerShip1_orange.png",
  "images/space_ships/playerShip1_red.png",
  "images/space_ships/playerShip2_blue.png",
  "images/space_ships/playerShip2_green.png",
  "images/space_ships/playerShip2_orange.png",
  "images/space_ships/playerShip2_red.png",
  "images/space_ships/playerShip3_blue.png",
  "images/space_ships/playerShip3_green.png",
  "images/space_ships/playerShip3_orange.png",
  "images/space_ships/playerShip3_red.png",
  "images/space_ships/spaceShips_001.png",
  "images/space_ships/spaceShips_002.png",
  "images/space_ships/spaceShips_003.png",
  "images/space_ships/spaceShips_004.png",
  "images/space_ships/spaceShips_005.png",
  "images/space_ships/spaceShips_006.png",
  "images/space_ships/spaceShips_007.png",
  "images/space_ships/spaceShips_008.png",
  "images/space_ships/spaceShips_009.png",
  "images/space_ships/ufoBlue.png",
  "images/space_ships/ufoGreen.png",
  "images/space_ships/ufoRed.png",
  "images/space_ships/ufoYellow.png",
  "images/space_ships/Parts/beam0.png",
  "images/space_ships/Parts/beam1.png",
  "images/space_ships/Parts/beam2.png",
  "images/space_ships/Parts/beam3.png",
  "images/space_ships/Parts/beam4.png",
  "images/space_ships/Parts/beam5.png",
  "images/space_ships/Parts/beam6.png",
  "images/space_ships/Parts/beamLong1.png",
  "images/space_ships/Parts/beamLong2.png",
  "images/space_ships/Parts/cockpitBlue_0.png",
  "images/space_ships/Parts/cockpitBlue_1.png",
  "images/space_ships/Parts/cockpitBlue_2.png",
  "images/space_ships/Parts/cockpitBlue_3.png",
  "images/space_ships/Parts/cockpitBlue_4.png",
  "images/space_ships/Parts/cockpitBlue_5.png",
  "images/space_ships/Parts/cockpitBlue_6.png",
  "images/space_ships/Parts/cockpitBlue_7.png",
  "images/space_ships/Parts/cockpitGreen_0.png",
  "images/space_ships/Parts/cockpitGreen_1.png",
  "images/space_ships/Parts/cockpitGreen_2.png",
  "images/space_ships/Parts/cockpitGreen_3.png",
  "images/space_ships/Parts/cockpitGreen_4.png",
  "images/space_ships/Parts/cockpitGreen_5.png",
  "images/space_ships/Parts/cockpitGreen_6.png",
  "images/space_ships/Parts/cockpitGreen_7.png",
  "images/space_ships/Parts/cockpitRed_0.png",
  "images/space_ships/Parts/cockpitRed_1.png",
  "images/space_ships/Parts/cockpitRed_2.png",
  "images/space_ships/Parts/cockpitRed_3.png",
  "images/space_ships/Parts/cockpitRed_4.png",
  "images/space_ships/Parts/cockpitRed_5.png",
  "images/space_ships/Parts/cockpitRed_6.png",
  "images/space_ships/Parts/cockpitRed_7.png",
  "images/space_ships/Parts/cockpitYellow_0.png",
  "images/space_ships/Parts/cockpitYellow_1.png",
  "images/space_ships/Parts/cockpitYellow_2.png",
  "images/space_ships/Parts/cockpitYellow_3.png",
  "images/space_ships/Parts/cockpitYellow_4.png",
  "images/space_ships/Parts/cockpitYellow_5.png",
  "images/space_ships/Parts/cockpitYellow_6.png",
  "images/space_ships/Parts/cockpitYellow_7.png",
  "images/space_ships/Parts/engine1.png",
  "images/space_ships/Parts/engine2.png",
  "images/space_ships/Parts/engine3.png",
  "images/space_ships/Parts/engine4.png",
  "images/space_ships/Parts/engine5.png",
  "images/space_ships/Parts/gun00.png",
  "images/space_ships/Parts/gun01.png",
  "images/space_ships/Parts/gun02.png",
  "images/space_ships/Parts/gun03.png",
  "images/space_ships/Parts/gun04.png",
  "images/space_ships/Parts/gun05.png",
  "images/space_ships/Parts/gun06.png",
  "images/space_ships/Parts/gun07.png",
  "images/space_ships/Parts/gun08.png",
  "images/space_ships/Parts/gun09.png",
  "images/space_ships/Parts/gun10.png",
  "images/space_ships/Parts/scratch1.png",
  "images/space_ships/Parts/scratch2.png",
  "images/space_ships/Parts/scratch3.png",
  "images/space_ships/Parts/turretBase_big.png",
  "images/space_ships/Parts/turretBase_small.png",
  "images/space_ships/Parts/wingBlue_0.png",
  "images/space_ships/Parts/wingBlue_1.png",
  "images/space_ships/Parts/wingBlue_2.png",
  "images/space_ships/Parts/wingBlue_3.png",
  "images/space_ships/Parts/wingBlue_4.png",
  "images/space_ships/Parts/wingBlue_5.png",
  "images/space_ships/Parts/wingBlue_6.png",
  "images/space_ships/Parts/wingBlue_7.png",
  "images/space_ships/Parts/wingGreen_0.png",
  "images/space_ships/Parts/wingGreen_1.png",
  "images/space_ships/Parts/wingGreen_2.png",
  "images/space_ships/Parts/wingGreen_3.png",
  "images/space_ships/Parts/wingGreen_4.png",
  "images/space_ships/Parts/wingGreen_5.png",
  "images/space_ships/Parts/wingGreen_6.png",
  "images/space_ships/Parts/wingGreen_7.png",
  "images/space_ships/Parts/wingRed_0.png",
  "images/space_ships/Parts/wingRed_1.png",
  "images/space_ships/Parts/wingRed_2.png",
  "images/space_ships/Parts/wingRed_3.png",
  "images/space_ships/Parts/wingRed_4.png",
  "images/space_ships/Parts/wingRed_5.png",
  "images/space_ships/Parts/wingRed_6.png",
  "images/space_ships/Parts/wingRed_7.png",
  "images/space_ships/Parts/wingYellow_0.png",
  "images/space_ships/Parts/wingYellow_1.png",
  "images/space_ships/Parts/wingYellow_2.png",
  "images/space_ships/Parts/wingYellow_3.png",
  "images/space_ships/Parts/wingYellow_4.png",
  "images/space_ships/Parts/wingYellow_5.png",
  "images/space_ships/Parts/wingYellow_6.png",
  "images/space_ships/Parts/wingYellow_7.png",
  "images/space_ships/Parts/_spaceParts_001 (1).png",
  "images/space_ships/Parts/_spaceParts_001 (10).png",
  "images/space_ships/Parts/_spaceParts_001 (11).png",
  "images/space_ships/Parts/_spaceParts_001 (12).png",
  "images/space_ships/Parts/_spaceParts_001 (13).png",
  "images/space_ships/Parts/_spaceParts_001 (14).png",
  "images/space_ships/Parts/_spaceParts_001 (15).png",
  "images/space_ships/Parts/_spaceParts_001 (16).png",
  "images/space_ships/Parts/_spaceParts_001 (17).png",
  "images/space_ships/Parts/_spaceParts_001 (18).png",
  "images/space_ships/Parts/_spaceParts_001 (19).png",
  "images/space_ships/Parts/_spaceParts_001 (2).png",
  "images/space_ships/Parts/_spaceParts_001 (20).png",
  "images/space_ships/Parts/_spaceParts_001 (21).png",
  "images/space_ships/Parts/_spaceParts_001 (22).png",
  "images/space_ships/Parts/_spaceParts_001 (23).png",
  "images/space_ships/Parts/_spaceParts_001 (24).png",
  "images/space_ships/Parts/_spaceParts_001 (25).png",
  "images/space_ships/Parts/_spaceParts_001 (26).png",
  "images/space_ships/Parts/_spaceParts_001 (27).png",
  "images/space_ships/Parts/_spaceParts_001 (28).png",
  "images/space_ships/Parts/_spaceParts_001 (29).png",
  "images/space_ships/Parts/_spaceParts_001 (3).png",
  "images/space_ships/Parts/_spaceParts_001 (30).png",
  "images/space_ships/Parts/_spaceParts_001 (31).png",
  "images/space_ships/Parts/_spaceParts_001 (32).png",
  "images/space_ships/Parts/_spaceParts_001 (33).png",
  "images/space_ships/Parts/_spaceParts_001 (34).png",
  "images/space_ships/Parts/_spaceParts_001 (35).png",
  "images/space_ships/Parts/_spaceParts_001 (36).png",
  "images/space_ships/Parts/_spaceParts_001 (37).png",
  "images/space_ships/Parts/_spaceParts_001 (38).png",
  "images/space_ships/Parts/_spaceParts_001 (39).png",
  "images/space_ships/Parts/_spaceParts_001 (4).png",
  "images/space_ships/Parts/_spaceParts_001 (40).png",
  "images/space_ships/Parts/_spaceParts_001 (41).png",
  "images/space_ships/Parts/_spaceParts_001 (42).png",
  "images/space_ships/Parts/_spaceParts_001 (43).png",
  "images/space_ships/Parts/_spaceParts_001 (44).png",
  "images/space_ships/Parts/_spaceParts_001 (45).png",
  "images/space_ships/Parts/_spaceParts_001 (46).png",
  "images/space_ships/Parts/_spaceParts_001 (47).png",
  "images/space_ships/Parts/_spaceParts_001 (48).png",
  "images/space_ships/Parts/_spaceParts_001 (49).png",
  "images/space_ships/Parts/_spaceParts_001 (5).png",
  "images/space_ships/Parts/_spaceParts_001 (50).png",
  "images/space_ships/Parts/_spaceParts_001 (51).png",
  "images/space_ships/Parts/_spaceParts_001 (52).png",
  "images/space_ships/Parts/_spaceParts_001 (53).png",
  "images/space_ships/Parts/_spaceParts_001 (54).png",
  "images/space_ships/Parts/_spaceParts_001 (55).png",
  "images/space_ships/Parts/_spaceParts_001 (56).png",
  "images/space_ships/Parts/_spaceParts_001 (57).png",
  "images/space_ships/Parts/_spaceParts_001 (58).png",
  "images/space_ships/Parts/_spaceParts_001 (59).png",
  "images/space_ships/Parts/_spaceParts_001 (6).png",
  "images/space_ships/Parts/_spaceParts_001 (60).png",
  "images/space_ships/Parts/_spaceParts_001 (61).png",
  "images/space_ships/Parts/_spaceParts_001 (62).png",
  "images/space_ships/Parts/_spaceParts_001 (63).png",
  "images/space_ships/Parts/_spaceParts_001 (64).png",
  "images/space_ships/Parts/_spaceParts_001 (65).png",
  "images/space_ships/Parts/_spaceParts_001 (66).png",
  "images/space_ships/Parts/_spaceParts_001 (67).png",
  "images/space_ships/Parts/_spaceParts_001 (68).png",
  "images/space_ships/Parts/_spaceParts_001 (69).png",
  "images/space_ships/Parts/_spaceParts_001 (7).png",
  "images/space_ships/Parts/_spaceParts_001 (70).png",
  "images/space_ships/Parts/_spaceParts_001 (71).png",
  "images/space_ships/Parts/_spaceParts_001 (72).png",
  "images/space_ships/Parts/_spaceParts_001 (73).png",
  "images/space_ships/Parts/_spaceParts_001 (74).png",
  "images/space_ships/Parts/_spaceParts_001 (75).png",
  "images/space_ships/Parts/_spaceParts_001 (76).png",
  "images/space_ships/Parts/_spaceParts_001 (77).png",
  "images/space_ships/Parts/_spaceParts_001 (78).png",
  "images/space_ships/Parts/_spaceParts_001 (79).png",
  "images/space_ships/Parts/_spaceParts_001 (8).png",
  "images/space_ships/Parts/_spaceParts_001 (80).png",
  "images/space_ships/Parts/_spaceParts_001 (81).png",
  "images/space_ships/Parts/_spaceParts_001 (82).png",
  "images/space_ships/Parts/_spaceParts_001 (83).png",
  "images/space_ships/Parts/_spaceParts_001 (84).png",
  "images/space_ships/Parts/_spaceParts_001 (85).png",
  "images/space_ships/Parts/_spaceParts_001 (86).png",
  "images/space_ships/Parts/_spaceParts_001 (87).png",
  "images/space_ships/Parts/_spaceParts_001 (88).png",
  "images/space_ships/Parts/_spaceParts_001 (89).png",
  "images/space_ships/Parts/_spaceParts_001 (9).png",
  "images/space_ships/Parts/_spaceParts_001 (90).png",
  "images/space_ships/Parts/_spaceParts_001 (91).png",
  "images/space_ships/Parts/_spaceParts_001 (92).png",
  "images/space_ships/Parts/_spaceParts_001 (93).png",
  "images/space_ships/Parts/_spaceParts_001 (94).png",
  "images/space_ships/Parts/_spaceParts_001 (95).png",
  "images/space_ships/Parts/_spaceParts_001 (96).png",
  "images/space_ships/Parts/_spaceParts_001 (97).png",
  "images/space_ships/Parts/_spaceParts_001 (98).png"
]


class ImageLoad:
    def __init__(self):
        self.image_dict = {}
        for name in list_image_name:
            image = pygame.image.load(name)
            # Sprawdzanie, czy obrazek ma kanał alfa i konwersja
            if image.get_alpha():
                self.image_dict[name] = image.convert_alpha()
            else:
                self.image_dict[name] = image.convert()

    def get_image(self, name, scale):
        image = self.image_dict.get(name)
        ret = None
        if not image:
            ret = None
        elif isinstance(scale, (list, tuple)):
            if len(scale) == 2:
                width, height = scale
                ret = pygame.transform.scale(image, (width, height))
            elif len(scale) == 1:
                percent = scale[0] / 100
                width = int(image.get_width() * percent)
                height = int(image.get_height() * percent)
                ret = pygame.transform.scale(image, (width, height))
        elif isinstance(scale, (int, float)):
            percent = scale / 100
            width = int(image.get_width() * percent)
            height = int(image.get_height() * percent)
            ret = pygame.transform.scale(image, (width, height))
        
        return ret
        